import { SystemTelemetry } from "./types"

export const defaultSystemTelemetry: SystemTelemetry = {
  ap: {
    id: "AP-01",
    name: "Access Point",
    online: true,
    sessionState: "idle",
    controlLocked: true,
    operatorName: "Operator",
    lastHeartbeat: new Date().toLocaleTimeString(),
  },
  ch: {
    id: "CH-01",
    label: "Communication Hub",
    online: true,
    endpoint: "192.168.0.204",
    signalStrength: 82,
    cameraOnline: false,
    securityState: "idle",
    lastHeartbeat: new Date().toLocaleTimeString(),
    bridgeProtocol: "ESP-NOW",
  },
  pd: {
    id: "PD-01",
    label: "Panel Device",
    online: true,
    protocol: "ESP-NOW",
    lastHeartbeat: new Date().toLocaleTimeString(),
    fault: null,
    channelCount: 6,
    channels: [
      {
        number: 1,
        label: "Circuit 1",
        phase: "A",
        gpio: 13,
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 2,
        label: "Circuit 2",
        phase: "A",
        gpio: 14,
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 3,
        label: "Circuit 3",
        phase: "B",
        gpio: 15,
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 4,
        label: "Circuit 4",
        phase: "B",
        gpio: 16,
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 5,
        label: "Circuit 5",
        phase: "C",
        gpio: 17,
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 6,
        label: "Circuit 6",
        phase: "C",
        gpio: 18,
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
    ],
  },
  measurements: {
    voltage: null,
    continuityStatus: "Unknown",
    phaseDetected: "Unknown",
    neutralGroundStatus: "Unknown",
    freshness: "No live data yet",
    current: null,
    power: null,
  },
  security: {
    alarmActive: false,
    intrusionDetected: false,
    auditTrailEnabled: true,
    remoteLockout: false,
    killSignalReady: true,
    lastAlarmTime: null,
  },
  camera: {
    online: false,
    latestImageUrl: null,
    lastCaptureTime: null,
    triggerSource: null,
  },
  eventLog: [
    {
      id: "evt-001",
      time: new Date().toLocaleTimeString(),
      source: "AP",
      target: "System",
      action: "Dashboard initialized",
      result: "Success",
      notes: "Loaded default telemetry model",
    },
  ],
}