import { SystemTelemetry } from "./types"
export const defaultSystemTelemetry: SystemTelemetry = {
  ap: {
    id: "UI-01",
    name: "User Interface",
    online: false,
    sessionState: "idle",
    controlLocked: true,
    operatorName: "Operator",
    lastHeartbeat: "Never",
  },
  ch: {
    id: "CH-01",
    label: "Communication Hub",
    online: false,
    endpoint: "",
    signalStrength: 0,
    cameraOnline: false,
    securityState: "idle",
    lastHeartbeat: "Never",
    bridgeProtocol: "ESP-NOW",
  },
  pd: {
    id: "PD-01",
    label: "Panel Device",
    online: false,
    protocol: "ESP-NOW",
    lastHeartbeat: "Never",
    fault: null,
    channelCount: 6,
    channels: [
      {
        number: 1,
        label: "Circuit 1",
        phase: "A",
        gpio: "GPIO 13",
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 2,
        label: "Circuit 2",
        phase: "B",
        gpio: "GPIO 14",
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 3,
        label: "Circuit 3",
        phase: "C",
        gpio: "GPIO 15",
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 4,
        label: "Circuit 4",
        phase: "D",
        gpio: "RX2 (GPIO 16)",
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 5,
        label: "Circuit 5",
        phase: "E",
        gpio: "TX2 (GPIO 17)",
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
      {
        number: 6,
        label: "Circuit 6",
        phase: "F",
        gpio: "GPIO 18",
        enabled: true,
        commandedState: "off",
        actualState: "off",
        continuity: "unknown",
        fault: null,
        lastCommand: "None",
        lastResponse: "None",
        testResult: "untested",
      },
    ],
  },
  measurements: {
    voltage: null,
    continuityStatus: "Unknown",
    phaseDetected: "Unknown",
    neutralGroundStatus: "Unknown",
    freshness: "No live data yet",
  },
  security: {
    alarmActive: false,
    intrusionDetected: false,
    auditTrailEnabled: true,
    remoteLockout: false,
    killSignalReady: true,
    lastAlarmTime: null,
  },
  camera: {
    online: false,
    latestImageUrl: null,
    lastCaptureTime: null,
    triggerSource: null,
  },
  eventLog: [
    {
      id: "evt-001",
      time: "Not yet available",
      source: "User Interface",
      target: "System",
      action: "Dashboard initialized",
      result: "Success",
      notes: "Loaded default telemetry model",
    },
  ],
}
 
